### ISSUE TITLE
rowClassName is overridden by default style.

### ISSUE THREAD

**Issue by HarleySalas** [icflorescu/mantine-datatable#192]
**Describe the bug**
rowClassName is overridden by default style.

**To Reproduce**
Create a DataTable.

create a `useStyles` hook with `createStyles` from `@mantine/core` and use it in your DataTable component. Add a field called `row` with a `backgroundColor` of red or something.

add `rowClassName={classes.row}`

**Expected behavior**
Rows should now be red.
However, the default `background-color` has a higher specificity.

Can add `!important` to resolve, but it should not be necessary. Following the same patterns that Mantine docs describes for custom components and styles would resolve these sort of issues.

**Comment by icflorescu** [comment]
Actually, this is a common problem with emotion-based UI frameworks.

In this case, the default style is overriding yours because it's applied with a selector like `.mantine-1cbzqls tr`, which is more specific than your class name (due to the ending `tr`).

Instead of using `!important`, you could increase your class specificity by defining it like so:

```ts
const useStyles = createStyles({
  row: { '&&': { backgroundColor: 'red' } },
});
```

This will override the default Mantine style.
 
See this on StackOverflow for more information: https://stackoverflow.com/questions/62660480/is-there-a-way-to-increase-specificity-by-adding-the-element-with-emotion

**Comment by NlightN22** [comment]
I get the same problem. I want to change background color on hover. And i have only one decision which i finded:
```
const useStyles = createStyles((theme) => ({
    blueishRow: {
        '&:hover': {
            backgroundColor: theme.colorScheme === 'dark' ? theme.colors.blue[9] + "!important" : theme.colors.blue[2] + "!important",
        },
    },
}))
```
Maybe i can do it better?
