### ISSUE TITLE
Improve accessibility of buttons and checkboxes used for pagination

### ISSUE THREAD

**Issue by mcmxcdev** [icflorescu/mantine-datatable#257]
**Is your feature request related to a problem? Please describe.**

Microsoft Edge has handy accessibility checks built-in and they detected these issues: 
![image](https://user-images.githubusercontent.com/16797721/232675809-ba70c7e3-4718-4b49-a62c-c61d455ac2f7.png)

**Describe the solution you'd like**
Back/Forward buttons for switching pages needs to have e.g. `aria-label` or `title` attribute set: https://dequeuniversity.com/rules/axe/4.4/button-name?application=axeAPI 

Checkboxes for records selection feature need to have a label, e.g. `aria-label` attribute since we don't want a visible label here: https://dequeuniversity.com/rules/axe/4.4/label?application=axeAPI

**Describe alternatives you've considered**
Ignore a11y, but it hurts the ecosystem

**Comment by icflorescu** [comment]
Thank you for raising this.

This should be fixed in a few minutes, as soon as `v2.4.3` hits the npm registry.
There are a few properties you can use to override the defaults:
- `allRecordsSelectionCheckboxProps`
- `getRecordSelectionCheckboxProps`
- `getPaginationControlProps`

I've also updated these examples in the docs website accordingly:
- [Pagination](https://icflorescu.github.io/mantine-datatable/examples/pagination)
- [Records selection](https://icflorescu.github.io/mantine-datatable/examples/records-selection)

**Comment by mcmxcdev** [comment]
Cool, that was very quick, thank you! Great to see some overridable defaults set, good solution.
