### ISSUE TITLE
Show ellipsed text on hover or onClick

### ISSUE THREAD

**Issue by Muhammad-Arsalan31** [icflorescu/mantine-datatable#386]
**Is your feature request related to a problem? Please describe.**
When a column is elliped the user can see the text by either clicking or on hover over that column. this can be done by expanding the row but what if the only user wants to see the column text only?

**Describe the solution you'd like**
we could use mantine built in tooltip component to display the text.
another option is to use the HoveCard component that can be used to create a custom layout.
**Describe alternatives you've considered**

**Additional context**
you can hover over the email column to see the ellipsed text by clicking on the icon.
https://elastic.github.io/eui/#/tabular-content/data-grid
![image](https://github.com/icflorescu/mantine-datatable/assets/31656210/5cac88de-159b-4ac6-bde7-fa0b66581c12)

**Comment by icflorescu** [comment]
In my opinion, this is really a very particular edge case that can (and should) be addressed in your usage scenario. 
I'd be reluctant to make the data table show a tooltip by default on every column with ellipsis, especially since this would make the component heavier in terms of cpu usage.  
What do you think?

**Comment by Muhammad-Arsalan31** [comment]
Yes, maybe you are right. the tooltip can easily be made with the render method. no need for adding extra logic. thanks.

Also thanks for amazing work on making this library really appreciate your efforts 🙂
