### ISSUE TITLE
Setting Height for table crahes

### ISSUE THREAD

**Issue by lecoqjacob** [icflorescu/mantine-datatable#407]
**Describe the bug**
If i remove height from my table, it doesnt throw a console error, with height set to like "50%" it throws an error on the scrollRef

**To Reproduce**

Create a table with smaller height than the page and rerender

**Expected behavior**
No Crash

**Screenshots**

![2023-08-11-202020_hyprshot](https://github.com/icflorescu/mantine-datatable/assets/9278174/bf34221f-44c4-4a18-8fce-6bc24787c2ce)

**Desktop (please complete the following information):**

![2023-08-11-203221_hyprshot](https://github.com/icflorescu/mantine-datatable/assets/9278174/354f34fc-3084-4c20-9d99-c0c6aa4f8f4c)

**Additional context**
Using latest of the lib

**Comment by icflorescu** [comment]
Can you please share what are the **exact** versions of `mantine-datatable` and `@mantine/*` packages?
Are you sure you're using the latest versions?

Nothing like this should happen in the latest version, as you can see in these example pages:
- [Scrollable vs. auto-height](https://icflorescu.github.io/mantine-datatable/examples/scrollable-vs-auto-height)
- [Complex usage](https://icflorescu.github.io/mantine-datatable/examples/complex-usage)

Ideally I'd like to know what's in the lockfile (i.e. `yarn.lock` or `package-lock.json`) rather than your `package.json`.

I'm asking because Mantine `6.0.18` [had a bug](https://github.com/icflorescu/mantine-datatable/issues/400) that could possibly [trigger this kind of error](https://github.com/icflorescu/mantine-datatable/issues/398).

**Comment by lecoqjacob** [comment]
When I get home I'm going to upgrade to 0.19 of mantine and get back to you. I had no idea it was mantine being funky, it just kept pointing to the code inside your library. I see mantine is locked at v18 so I will see if 19 fixes it. Thank you for the quick response!

**Comment by icflorescu** [comment]
I assume everything worked with the new version of Mantine, so I am going to close this for now.
Please feel free to reopen if necessary.
