### ISSUE TITLE
Allow using index for idAccessor function

### ISSUE THREAD

**Issue by DoubleJ-G** [icflorescu/mantine-datatable#419]
**Is your feature request related to a problem? Please describe.**
I am using a data table with input fields to edit repeatable data such as {key: string, value: string}[]. I do not necessarily have an id field and if I base the accessor on key or value it causes a re-render whenever I change an input.

**Describe the solution you'd like**
I would propose changing the idAccessor prop to `string | ((record: T, index: number) => Key);` and passing the index to the function constructing the key.

**Describe alternatives you've considered**
I could manually add an id/unique field to the data but I would most likely just be auto incrementing/using the index number anyway.  

**Additional context**
I know using the index of an array as a key for React is not best practice but there are some situations which require it and this would at least give you the option to use it.

**Comment by icflorescu** [comment]
Hey, @DoubleJ-G, sorry for being unable to reply sooner, but I had a lot on my mind lately, including releasing V7.

Changing the `idAccessor` prop signature to something that includes the index would be a lot of work and complicate things internally. So, I am kind of reluctant to this, especially since - as you mentioned - using the index as a key is kind of a React anti-pattern.

If that's really what you want and need, you could alternatively:
- add an `id` to the data, as you said
- provide an `idAccessor` function that searches of the record in your data and returns its `id`

None of them are ideal, but both of them are working. The 1st one is probably faster, the 2nd is probably cleaner.
