### ISSUE TITLE
Mantine V7 Support

### ISSUE THREAD

**Issue by aaly00** [icflorescu/mantine-datatable#420]
Curious if there are plans to support Mantine v7 since it's now released ?

**Comment by ericschmar** [comment]
It looks like the removal of `createStyles` is a bare minimun necessity.

**Comment by beeman** [comment]
> I followed the Getting Started Steps here: https://icflorescu.github.io/mantine-datatable/getting-started
> 
> And I'm getting the following error TS error (guessing this is an issue with Mantine v7?):
> 
> Error:
> 
> Server Error TypeError: (0 , mr.createStyles) is not a function
> 
> This error happened while generating the page. Any console logs will be displayed in the terminal window. Call Stack ....

This is because Mantine v7 handles styling completely differently, as you can see in the [migration guide](https://mantine.dev/changelog/7-0-0/#migration-to-native-css). 

The current version of `mantine-datatable` is not going to work with v7 so either stay with Mantine v6 or look for another way to handle your tables.

**Comment by adnanlah** [comment]
> > I followed the Getting Started Steps here: https://icflorescu.github.io/mantine-datatable/getting-started
> > 
> > And I'm getting the following error TS error (guessing this is an issue with Mantine v7?):
> > 
> > Error:
> > 
> > Server Error TypeError: (0 , mr.createStyles) is not a function
> > 
> > This error happened while generating the page. Any console logs will be displayed in the terminal window. Call Stack ....
> 
> This is because Mantine v7 handles styling completely differently, as you can see in the [migration guide](https://mantine.dev/changelog/7-0-0/#migration-to-native-css). 
> 
> The current version of `mantine-datatable` is not going to work with v7 so either stay with Mantine v6 or look for another way to handle your tables.

What can be the reasons that they are not going to work with v7?

**Comment by beeman** [comment]
> > > I followed the Getting Started Steps here: https://icflorescu.github.io/mantine-datatable/getting-started
> > > And I'm getting the following error TS error (guessing this is an issue with Mantine v7?):
> > > Error:
> > > Server Error TypeError: (0 , mr.createStyles) is not a function
> > > This error happened while generating the page. Any console logs will be displayed in the terminal window. Call Stack ....
> > 
> > 
> > This is because Mantine v7 handles styling completely differently, as you can see in the [migration guide](https://mantine.dev/changelog/7-0-0/#migration-to-native-css).
> > The current version of `mantine-datatable` is not going to work with v7 so either stay with Mantine v6 or look for another way to handle your tables.
> 
> What can be the reasons that they are not going to work with v7?

They moved from 'emotion' to 'css modules' for styling, so a lot of Mantine's internals changed. 

I recommend reading the Mantine v7 changelog and migration guide to get a better idea.

**Comment by ericschmar** [comment]
@icflorescu Can we get an ETA on supporting Mantine 7.0? Obviously very appreciative of your work on this open source project--just looking for some confirmation from you.

**Comment by beeman** [comment]
> @icflorescu Can we get an ETA on supporting Mantine 7.0? Obviously very appreciative of your work on this open source project--just looking for some confirmation from you.

I just did a one-time sponsorship to @icflorescu as a thank you and a motivation to work on this. I suggest others do the same - if you can justify the expense. 

Being a library maintainer myself, I know this can be a very welcome gesture :)

**Comment by ericschmar** [comment]
> > @icflorescu Can we get an ETA on supporting Mantine 7.0? Obviously very appreciative of your work on this open source project--just looking for some confirmation from you.
> 
> I just did a one-time sponsorship to @icflorescu as a thank you and a motivation to work on this. I suggest others do the same - if you can justify the expense.
> 
> Being a library maintainer myself, I know this can be a very welcome gesture :)

Yes. This is being used internally at my work and I'm pressing for a donation.

**Comment by ericschmar** [comment]
Another question here: With the addition of post-css being a dependency of Mantine now, will mantine-datatable be willing to add it as well? It would make the styling much simpler to convert over from `useStyles`.

**Comment by beeman** [comment]
> Another question here: With the addition of post-css being a dependency of Mantine now, will mantine-datatable be willing to add it as well? It would make the styling much simpler to convert over from `useStyles`.

From my experience of converting my [humble Mantine package](https://github.com/pubkeyapp/solana-wallet-adapter-mantine-ui) there's basically no choice - you'll have to use 'css modules', so no more `useStyles`.

**Comment by ericschmar** [comment]
> > Another question here: With the addition of post-css being a dependency of Mantine now, will mantine-datatable be willing to add it as well? It would make the styling much simpler to convert over from `useStyles`.
> 
> From my experience of converting my [humble Mantine package](https://github.com/pubkeyapp/solana-wallet-adapter-mantine-ui) there's basically no choice - you'll have to use 'css modules', so no more `useStyles`.

Do you have a recommended method of going about doing that?

**Comment by beeman** [comment]
> > > Another question here: With the addition of post-css being a dependency of Mantine now, will mantine-datatable be willing to add it as well? It would make the styling much simpler to convert over from `useStyles`.
> > 
> > 
> > From my experience of converting my [humble Mantine package](https://github.com/pubkeyapp/solana-wallet-adapter-mantine-ui) there's basically no choice - you'll have to use 'css modules', so no more `useStyles`.
> 
> Do you have a recommended method of going about doing that?

Yes, as that's what's recommended in the Mantine migration guide so I figured it makes most sense to stick with that.

**Comment by ericschmar** [comment]
@icflorescu I did an initial pass pulling out all the styles into their own `.css` files and referencing them in their individual components. I am not an expert by any means, but I did a ton of the leg work just copying and converting. 

I tried pushing my branch, but I don't have permissions. Just let me know how you prefer to get these changes, and I can pass them along to you.

**Comment by beeman** [comment]
> @icflorescu I did an initial pass pulling out all the styles into their own `.css` files and referencing them in their individual components. I am not an expert by any means, but I did a ton of the leg work just copying and converting.
> 
> I tried pushing my branch, but I don't have permissions. Just let me know how you prefer to get these changes, and I can pass them along to you.

When contributing to projects from other people, the best practices is to fork first, make changes in a local branch, then push that branch to your fork and create a pull request.

If it's new to you, happy to walk you through it over Discord chat (link is in my profile)

**Comment by ericschmar** [comment]
> > @icflorescu I did an initial pass pulling out all the styles into their own `.css` files and referencing them in their individual components. I am not an expert by any means, but I did a ton of the leg work just copying and converting.
> > I tried pushing my branch, but I don't have permissions. Just let me know how you prefer to get these changes, and I can pass them along to you.
> 
> When contributing to projects from other people, the best practice is to fork first, make changes in a local branch, then push that branch to your fork and create a pull request.
> 
> If it's new to you, happy to walk you through it over Discord chat (link is in my profile)

Ahh. I can try that, sure. I'll let you know if I have any issues.

**Comment by ArjunAtlast** [comment]
+1

**Comment by icflorescu** [comment]
Sorry for being unable to come up with a reply last week.

### CONTEXT

As most of you already know, Mantine v7 came up with [a significant number of breaking changes, most of them referring to how styling is implemented](https://mantine.dev/changelog/7-0-0/).

As some of you know, `mantine-datatable` is one of my dearest open-source projects, has quite a large code-base, and while it has over 650 GitHub stars and 35k npm downloads per month, I'm still [struggling with raising enough funds](https://github.com/sponsors/icflorescu) to be able to dedicate as much time as I'd like to the project, despite the fact that it's [being used by lots of startups and developers](https://icflorescu.github.io/mantine-datatable/who-is-using-mantine-datatable) worldwide.

To put it bluntly, building and maintaining successful open-source projects doesn't pay my bills, or maybe I wasn't good enough so far at raising enough awareness and converting it into sponsorship income.

The fact that I recently lost a dear family member didn't help my ability to focus on the project over the last couple of weeks.

### WHAT'S NEXT

That being said, yes, I'm certainly planning to upgrade mantine-datatable to fully support Mantine V7 soon.
Can't give a time estimate for this, because - for the aforementioned reasons - there are other things that require my time and energy at the moment.
But I certainly will.
And I can't wait to do it!

Your help and understanding truly matters, and I'll take this opportunity to thank you, @beeman, for your one-time sponsorship!

### QUICK ANSWERS

@aaly00 
> Curious if there are plans to support Mantine v7 since it's now released ?

Yes.

@blentz100 
> And I'm getting the following error TS error (guessing this is an issue with Mantine v7?):

Yes, it's an issue with Mantine v7.

@adnanlah 
> What can be the reasons that they are not going to work with v7?

It's in the [changelog / migration guide](https://mantine.dev/changelog/7-0-0/#migration-to-native-css) quoted by @beeman.

@ericschmar 
> Can we get an ETA on supporting Mantine 7.0? Obviously very appreciative of your work on this open source project--just looking for some confirmation from you.

I'm afraid not, due to the aforementioned reasons.
But it's coming.

> This is being used internally at my work and I'm pressing for a donation.

It would mean a lot.

> PR is found here: https://github.com/icflorescu/mantine-datatable/pull/422

Thanks a lot! will take a look at it as soon as I am able.

Special thanks to @beeman and @ericschmar. You're special. Especially since there are so few people who understand that open-source is a joint effort and it doesn't mean the authors have a moral obligation to work for the benefit of others, come up with bug-fixes, do maintenance, write docs, or provide "working examples" - all of it, for free.  

Thank you all, again, for using `mantine-datatable`, for starring the repo, for spreading the word and sponsoring me.
I wouldn't be able to keep maintaining this project without [your support](https://github.com/sponsors/icflorescu).

**Comment by dlgoodchild** [comment]
@ericschmar did you manage to perform the `npm install` or `build` your fork?

**Comment by ericschmar** [comment]
> @ericschmar did you manage to perform the `npm install` of the mantine-datatable/package or `build` your fork?

I did npm install, but never attempted to build. My goal was to just start the conversion process and have a maintainer who knows more about building packages (and testing them) continue the work.

**Comment by blentz100** [comment]
@beeman Thanks for explaining what's going on. I'll try to use Mantine v6 then. I'm brand new to Mantine so I didn't realize that v7 just came out and would potentially introduce breaking changes.

**Comment by paulm17** [comment]
Some disclosure: I'm running a forked copy of mantine v7 for my own purposes.  This allows me some leverage to operate with more latitude and more quickly 😄.  

Thanks to the works of @ericschmar that took care of the css.  Once I understood how Mantine structures components internally, I was able to quickly duplicate this process among all the components.

So far, I have only validated the first basic example.  But when I create a storybook for all of them and verify they are all working.  I will then follow up with a repo.  So perhaps someone else can take this over the finish line?

Basic example:
![Image](https://i.ibb.co/RYXYJN9/Screenshot-2023-09-30-at-13-16-17.png)

So far I have only used 1 instance of @ts-ignore to ensure this successfully builds.  There are a couple of issues, I still need to resolve.

Build:
![Build](https://i.ibb.co/SRHGZQY/Screenshot-2023-09-30-at-13-53-06.png)

**Comment by icflorescu** [comment]
In addition to my [comment above](https://github.com/icflorescu/mantine-datatable/issues/420#issuecomment-1735931001), I'd also like to thank @usequantumai and @Mikkelzu for their donations 📢

🔥 So far, **good people have donated $115 towards the cause** 🙏, so, if this is the start of a trend 🤞, I'll soon be able to shift my focus back to this project for a while!

Perhaps this thread is not the best place to do it, but I'll do my best to keep you up to date with the progress of the campaign.

---

Also, related to future Mantine V7 support, I think I'm going to bump the current package version to 6.x and keep the major in sync with Mantine core. In other words, `mantine-datatable` v6 will be compatible with `@mantine/core` v6 and `mantine-datatable` v7 will work with `@mantine/core` v7.

**Comment by ericschmar** [comment]
@icflorescu Thank you for communicating directly about your needs and intention--I really appreciate it. Do you have a dollar amount you're looking for before you can resume work on this project? 

Additionally, I know in the past the Mantine developers have been fine leaving this as a separate project, but in light of the challenges with maintaining open source projects, I wonder if it's worth revisiting the inclusion of Mantine DataTable as part of the core Mantine library (if not core, an auxilary package similar to the carousel/dropzone)?

**Comment by Nikhilchandra-Rathod** [comment]
Hello,

Could you please give timeline for Mantine 7 support. My all applications already updated to Mantine 7 but only Mantine Datatable pages remaining to upgrade and I am waiting for one month to any progress for it.
If you can provide timeline so It would be great and I can decide to stick with this library or move to other library.

Thanks.

**Comment by dlgoodchild** [comment]
@icflorescu if I could get an answer with information on issues #425, then I'd be happy to start working on the the upgrade to v7.

**Comment by KevinVandy** [comment]
Hey, I'm somewhat on the other side of the Mantine v7 upgrade for mantine-react-table. It was a bit brutal, but had help from the Mantine community. Maybe we can learn from each other's patterns. I'm still not sure what the best practices are.

**Comment by dlgoodchild** [comment]
@icflorescu I appreciate everything you're saying and I think I can speak on behalf of everyone on this thread that we can wait out a couple of weeks. I do think if there was more of a community of contributors then you wouldn't feel the entire burden of responsibility on your shoulders alone. I was literally ready to dive right in and get a PR opened, but I hit many a road block. I think in light of how v7 has created an almost unreasonable demand on your time that it is fitting to look at making community contributing to mantine-datatable the norm and not an exception. Happy to help.

**Comment by icflorescu** [comment]
### STATUS UPDATE

[Mantine ContextMenu](https://icflorescu.github.io/mantine-contextmenu/) migration is almost done - I hope to have it ready tomorrow the latest, then I'll move to the DataTable and reuse much of the work and gained knowledge.

![Mantine ContextMenu migration to V7](https://github.com/icflorescu/mantine-datatable/assets/581999/add02e54-d622-405f-920f-956803f41e7b)

**Comment by icflorescu** [comment]
@KevinVandy, thanks for dropping by and thanks again for being one of the two monthly sponsors 🤗

> It was a bit brutal, but had help from the Mantine community. Maybe we can learn from each other's patterns. I'm still not sure what the best practices are.

Agreed.

As mentioned a couple of times above, I'm currently in the process of migrating [Mantine ContextMenu](https://icflorescu.github.io/mantine-contextmenu/). Yes, it is a bit brutal - especially if you want to make sure everything works without breaking RSC.

There's one nice thing I noticed when testing Mantine V7 in Next.js with the new app router & RSC: when you wrap your content in a `<MantineProvider>` in your layout file, you don't have to add the `use client` directive on top, despite the fact that the provider is obviously a client component.

It's probably one of the reasons they provide an `unbundled` version of the code (for both `cjs` and `esm`), and each client component in the transpiled code comes with the `use client` directive already included.
Mixing "client" and "server" components/code in a bundle wouldn't be possible, a thing that never occurred to me before, but bumped into while working at the upgrade.

Regarding CSS, since I remember you asking me about it on LI a few months ago, there's not that much CSS in Mantine ContextMenu, but the DataTable obviously comes with a bit more. I'll be using PostCSS for both of them, but I'm yet unsure whether to use CSS modules or not.

In the build script of the `alpha` version of Mantine ContextMenu V7 I'm simply compiling the TypeScript code with `tsc` and processing the styling with `postcss` (and a nice `postcss-import` plugin), but I did not use CSS modules, mostly because it can't be done with plain `tsc`, and I didn't feel like concocting an `esbuild` or Parcel config.

I hope this will help you and I'm looking forward to your feedback.

**Comment by icflorescu** [comment]
### Mantine DataTable V7.1 is available! 🎉😃🎉

[![Mantine DataTable V7.1](https://github.com/icflorescu/mantine-datatable/assets/581999/72111cde-0404-467c-a333-aa68129b1a24)](https://icflorescu.github.io/mantine-datatable/)

If you're still using [Mantine V6](https://v6.mantine.dev/), stay on `mantine-datatable@6` and refer to the old documentation website that has been archived here: [icflorescu.github.io/mantine-datatable-v6](https://icflorescu.github.io/mantine-datatable-v6/)
