### ISSUE TITLE
onCellClick is not triggered when clicked on checkbox cell

### ISSUE THREAD

**Issue by bcalik** [icflorescu/mantine-datatable#427]
**Is your feature request related to a problem? Please describe.**
I use the `selectedRecords` feature to enable row selection and show checkboxes. I would like to select the checkbox even when a user clicks on the cell in which the checkbox is located so that I can expand the clickable area. I tried using the `onCellClick` callback, but it's not triggered when clicked on that cell.

**Describe the solution you'd like**
`onCellClick` should be called even on the checkbox cell.

**Describe alternatives you've considered**
This feature could be enabled by default for better UX, instead of customization via `onCellClick`.

**Additional context**
None

**Comment by icflorescu** [comment]
The `onCellClick` handler also receives `column` and `columnIndex`, which wouldn't have sense for the selection cell column, so I don't like the idea of triggering it when the user clicks on the checkbox.

However, I do see your point that sometimes increasing the clickable area could be useful.

Which is why, starting with `v7.1.6`, you can set the `selectionTrigger` DataTable property to `'cell'`: https://icflorescu.github.io/mantine-datatable/examples/records-selection/#maximizing-the-selection-trigger-area-to-the-entire-cell

Please note that I only implemented this in V7.
I don't have the time and energy to backport this to V6, but if you do and you're still using Mantine V6, feel free to come up with a PR.

Thanks a lot!
