### ISSUE TITLE
useref for Table

### ISSUE THREAD

**Issue by codetestmg** [icflorescu/mantine-datatable#457]
Thanks for the library.

I have one feature implementation where i need to export as excel .So i need to use useref for table .

As per document , i can use body ref not table ref .Is there any way to add ref to table

**Comment by icflorescu** [comment]
If a property called `tableRef` proves to be useful, maybe we could expose it.
However, you shouldn't rely on it to export the data (since it could be formatted in ways that are unsupported by your export workflow).

Whenever I had to export data in my projects, I always did it by parsing the actual records.

**Comment by codetestmg** [comment]
@icflorescu  I agree with your point . If you think exposing tableRef  wouldn't be an issue then I would expect to expose it so it might help to access table dom .

Thanks

**Comment by jerebtw** [comment]
@icflorescu: Is it possible to export a reference to the pagination? So I can add controls between the record count and the page switch button?
