### ISSUE TITLE
Pin columns on the left side

### ISSUE THREAD

**Issue by wagnergerald** [icflorescu/mantine-datatable#477]
**Is your feature request related to a problem? Please describe.**
We are developing an application with the main menu and the user attention on the left hand side of the screen/UI.
To minimise the mouse travel of our users we would like place the action buttons of the table on the left and also want to pin the first _n_ columns of the table.

**Describe the solution you'd like**
It would be great to allow also pinning of columns on the left side, e.g. the first n columns.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by lukasbash** [comment]
This feature would be awesome! Would need this too ..

**Comment by lukasbash** [comment]
Any update on this? @icflorescu 

Even a property `pinFirstColumn` would be a good start instead of allowing the first `n` columns to be pinned. I assume calculating the space to the right and left for more than one column could be complex to calculate as the column width can grow dynamically.

**Comment by icflorescu** [comment]
@lukasbash Even a `pinFirstColumn` would be a bit more difficult to implement than `pinLastColumn`, due to the fact that each row can optionally contain a selection checkbox column before the first "user column", whose width is also dynamic, depending on a number things, such as the configured theme, `allRecordsSelectionCheckboxProps` and `getRecordSelectionCheckboxProps`, to name a few.

In other words, if a provided `pinFirstColumn` property would be `true`, the first "user column" would need to have a right shadow and be positioned with `sticky` and a dynamic `left` value equal to the selection column width (if present, or zero otherwise).  

I'm not 100% sure, but I believe this **could be implemented by computing the width of the selection column at render time, if present**.

I'll give it a try when I'll find the necessary time... **or maybe you could give it a go**. What do you think?

**Comment by icflorescu** [comment]
Going to close this for now, as `7.4.1` comes with `pinFirstColumn`.
See example page here: https://icflorescu.github.io/mantine-datatable/examples/pinning-the-first-column/

That being said, a PR to bring the option of pinning the first/last `n` columns would still be welcomed.
