### ISSUE TITLE
Checkbox inside filter Popover does not work

### ISSUE THREAD

**Issue by AtefBellaaj** [icflorescu/mantine-datatable#481]
**Describe the bug**
Checkboxes do not work in filter.

**To Reproduce**
1. add a checkbox as a filter component in columns defintion.
2. add a state to control the checkbox
3. Click on check box 
4. nothing happens...

**Expected behavior**
The checkbox should work properly 

**Screenshots**
![image](https://github.com/icflorescu/mantine-datatable/assets/10587636/91987c3a-05a2-413c-8390-f4a6a81e7c6e)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome :Version 119.0.6045.160 (Official Build) (64-bit)
- Version Datatable version ^7.1.7

**Additional context**
Since the filter uses a Mantine PopOver, i reproduced the error with a simple popover and a checkbox somewhere else. 
To reproduce the error, just add (like in the datatable code pase) add  onClick={(e) => e.preventDefault()}. I think this is the source of the problem. [line of code](https://github.com/icflorescu/mantine-datatable/blob/dfa9c52c14ae57965c69a3d55b211eae169055e6/package/DataTableHeaderCellFilter.tsx#L32C22-L32C22)

**Comment by icflorescu** [comment]
Thanks a lot for bringing this to my attention.
The issue should be fixed in the latest version, check the age column filter on this example: https://icflorescu.github.io/mantine-datatable/examples/searching-and-filtering.

Can't remember exactly, but I assume the `onClick={(e) => e.preventDefault()}` was there to prevent accidentally triggering the sort when clicking inside the popup. Should have used `.stopPropagation()` instead.
