### ISSUE TITLE
Delete selected row doesn't remove the row from selectedRecords

### ISSUE THREAD

**Issue by sonia-khazraei** [icflorescu/mantine-datatable#499]
**Describe the bug**
When I delete a selected row from state the row itself is removed in the table but the selected records is not updated and therefore the row after my deleted row exist in  selected rows
because I count the selected rows I found that it doesn't refresh

How can I remove the selected id from the list of selected rows?

**Comment by icflorescu** [comment]
Removing a record from the `selectedRecords` array falls within your responsibility as a developer.
You manage the `selectedRecords` array in the same manner you're managing the `records` state. For instance, here's a one-liner:

```ts
setSelectedRecords((selectedRecords) => selectedRecords.filter(({ id }) => id !== idToRemove));
```

If you're wondering why the records aren't removed automatically, that's because - for instance, when you're using pagination (in which case `records` only contains the **active** page), you might want to keep track of a selection spanning multiple pages, so you can batch an operation.

Think of how Gmail works: you can select some emails on a page, then move to the next page and select more emails, then delete **all** the emails you have selected, regardless of whether they are currently visible or not.

Does this answer your question?

**Comment by icflorescu** [comment]
Will close this for now.
Please feel free to reopen - or better yet - start a [new discussion in Q&A](https://github.com/icflorescu/mantine-datatable/discussions/new?category=q-a) if the above doesn't answer your question.

Thanks!
